[package]
name = "conwayrs"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MIT"
authors = ["envis10n <envis10n@envis10n.dev>"]

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
fastrand = "2.5.0"
pixels = "0.17.2"
winit = "0.30.13"
winit_input_helper = "0.17.0"
